<template>
<v-content id="use-cases">
  <v-container fluid >

      <div class="usecases" style="width:810px; margin: 0px auto 35px auto;font-size:16px; text-align:justify;">
          <h1 style="color: #6898A8; font-size: 38px; ">Use cases</h1>
          <div>
            This page provides a number of use cases to highlight the functionality in gene.iobio. These use cases make use of modified alignments for the Platinum trio data set that allow certain scenarios and functionality to be investigated. Each of the use cases below has a brief description of the problem at hand, and the gene name links to a screencast demonstrating the use case. For manual inspection, click <a href="http://newgene.iobio.io/#?rel0=proband&rel1=mother&rel2=father&gene=RAI1&name0=&vcf0=http://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam0=http://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.bam&name1=&vcf1=http://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam1=http://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12891.bam&name2=&vcf2=http://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam2=http://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12892.bam" target="_app">here</a> and gene.iobio will be launched with the Platinum data preloaded.
          </div>
            <ul  style="list-style-type: none;">
              <a name="RAI1" id="RAI1" ref="RAI1"></a>
              <li><h3><a href="https://www.youtube.com/watch?v=vsnv6YU1gDc">RAI1 - recessive variant</a></h3>
                <span class="inline">
                  Simple view of a <strong>recessive variant</strong>, pathogenic in clinvar.
                  <div style="padding:5px;">

                    <img src="assets/images/usecases/rai1.png" width="250px" style="float:left;padding-right:10px;"/>

                    <div style="padding-top:70px;"> All three members of the trio have a single variant colored in red, indicating that SnpEff has annotated this as a 'High Impact' variant.  When hovering over the variant in the proband card, the variant is circled in the variant cards for both the mother and the father. The basic information displayed for the parents indicates that they are heterozygous for the variant and the proband is homozygous, leading to the conclusion that this is a <strong>recessive</strong> variant.
                    </div>

                    <div style="padding-top:70px;">
                      This information can also be gleaned by looking in the 'Rank Variants' card. The 'Inheritance' row indicates all recessive variants with a unique icon.
                    </div>

                  </div>
               </span>
          </li >

            <a name="MYLK2" id="MYLK2" ref="MYLK2"></a>
            <li style="clear:both;"><h3><a href="https://www.youtube.com/watch?v=l-YsG1C6TkI">MYLK2 - real-time variant calling</a></h3>
              <div class="inline">
                This gene is used to demonstrate real-time variant calling using the provided alignments.
                <img src="assets/images/usecases/mylk2_a.png" width="275px" align="left" style="padding-right:5px;"/>
                For many reasons, it is possible that the provided variant file is missing variants that are present in the sample. For example, if conservative filtering criteria were imposed in the calling pipeline, some real variants may have been sacrificed to ensure a low false discovery rate. By clicking the <strong>'Call from alignments'</strong> button, real-time variant calling is performed on the alignments using Freebayes.

                <br style="clear:both;">

                <img src="assets/images/usecases/mylk2_b.png" width="300px" align="left" style="padding-top:20px; padding-right:5px;" />
                <div style="padding-top:20px;">
                 The newly discovered variant is annotated as being 'likely pathogenic' in ClinVar and is a de novo variant in the proband (this variant is not discovered in the parents) and so is likely a variant that is important to discover. The original variant calls were generated by performing 'pooled' calling, i.e. the variant calling algorithm used alignments from all three members of the trio when calling variants. The fraction of reads containing the variant allele is very low in this case, since only one chromosome in six has the variant. When called in gene.iobio, only the proband reads are used and so half of the chromosomes contain the variant allele, increasing the fraction of variant observations and generating a variant call with a higher quality than in the pooled case.
                </div>

              </div>

            </li>

            <a name="AIRE" id="AIRE" ref="AIRE"></a>
            <li style="clear:both;"><h3><a href="https://www.youtube.com/watch?v=MxIyc23HGxc">AIRE - low coverage alignments</a></h3>
              <div class="inline" >
                Variants can be missed as a result of <strong>low coverage</strong> in the alignments.
                <img src="assets/images/usecases/aire.png" width="300px" align="left" style="padding-top:20px; padding-right:5px;" />
                <div class="inline" style="padding-top:20px;">Both parents have a heterozygous SNP variant that is annotated as 'likely pathogenic' in ClinVar. The cross at this location in the proband indicates that the child does not have this variant, but the coverage track shows that the proband has a drop in coverage at exactly this location. Zooming into this exon shows this coverage drop very clearly. It is possible that the proband is homozygous for this variant, potentially resulting in a recessive disorder, but due to the lack of coverage, we cannot draw a conclusion, one way or the other.
                </div>
                </div>
            </li>

            <a name="PDGFB" id="PDGFB" ref="PDGFB"></a>
            <li style="clear:both;"><h3><a href="https://www.youtube.com/watch?v=k_nfrXgP-N0">PDGFB - alternative transcripts</a></h3>
              <div class="inline">By default, when a gene is loaded, the canonical transcript is displayed and the SnpEff annotations applied to the variants are applicable to this transcript. There are no variants in the 'Rank Variants' table that appear to be interesting. From the transcript drop-down menu, <strong>select the third transcript (ENST00000381551.4).</strong>
                <br>
                <img src="assets/images/usecases/pdgfb_a.png" width="600px" align="center" style="padding-top:20px;padding-bottom:20px;" />
                <br>

                <span>One of the intronic deletions now falls into exonic sequence. When changing transcript, SnpEff is used in real-time to generate annotations for the new transcript and, in this case, the original annotation of 'modifier intron variant' has become 'high impact frameshift variant'. Depending on the actual transcript in the proband, this variant could be very important.</span>
                <br>
                <img src="assets/images/usecases/pdgfb_b.png" width="800px" align="center" style="padding-top:20px;" />

              </div>
            </li>

            <!-- PDHA1 variant found using 'lactic acidosis' phenotype in phenolyzer -->
            <a name="PDHA1" id="PDHA1" ref="PDHA1"></a>
            <li style="clear:both;"><h3><a href="https://www.youtube.com/watch?v=MxIyc23HGxc">PDHA1 - phenotype driven analysis</a></h3>
              <div class="inline">
                Variant analysis can be directed using phenotype information using the <a href="http://phenolyzer.usc.edu">Phenolyzer</a> from Kai Wang's group at <a href="http://genomics.usc.edu/">USC</a>, which is integrated in gene.iobio. For example, consider a patient presenting with lactic acidosis. Which genes should be interrogated for this case?
                <img src="assets/images/usecases/pdha1_a.png" width="250px" align="left" style="padding-top:10px; padding-right:5px;" />
                <div class="inline" style="padding-top:20px">
                  From the left panel, select the 'Genes' button and in the Phenolyzer box, enter the phenotype (lactic acidosis) and press 'Run'. <a href="http://phenolyzer.usc.edu">Phenolyzer</a> is then run (note that this operation is only available for academic or non-profit use) and generates a ranked list of genes. By default, the top 30 ranked genes are added to the top gene.iobio panel and the top ranked gene (BCS1L) is automatically loaded and analyzed.
                </div>
                <div class="inline" style="padding-top:20px">
                  There are no variants in this gene that appear interesting, so the next gene (TTPA) can be selected from the top list. Again, there are no variants that stand out as being important, so we move on to the next gene in the list - PDHA1 (as shown in the image below).
                </div>
                <img src="assets/images/usecases/pdha1_b.png" width="750px" align="left" style="padding-top:30px; padding-right:5px;" />
                <div class="inline" style="padding-top:20px">
                  Now, in this gene, we see a missense, heterozygous <i>de novo</i> variant, that is not seen in either the 1000 Genomes or ExAC and is marked as <i>deleterious</i> by SIFT and <i>probably_damaging</i> by PolyPhen. This has a good chance of being the causative variant and it only took looking in three genes to find the variant.
                </div>
              </div>
            </li>
          </ul>
      </div>
  </v-container>
</v-content>
</template>

<script>

export default {
  name: 'use-cases',
  components: {
  },
  props: {
    paramTopic:             null
  },
  data() {
    return {
    }
  },
  mounted: function() {
   if (this.paramTopic) {
      this.scrollMeTo(this.paramTopic)
    }
  },
  watch:  {
    paramTopic: function() {
      if (this.paramTopic) {
        this.scrollMeTo(this.paramTopic)
      }
    }
  },
  methods: {
    scrollMeTo: function(refName) {
      let self = this;
      var top =        $('#use-cases ' + '#' + refName)[0].offsetTop;
      setTimeout( function() {
        window.scrollTo(0, top);
      }, 1000)


    }
  }
}
</script>